name: check_changed_articles

on:
  pull_request:

jobs:
  # -------------------------------------------------------------
  # Event `pull_request`: Returns all changed pull request files.
  # --------------------------------------------------------------
  changed_files:
    # NOTE:
    # - This is limited to pull_request* events and would raise an error for other events.
    # - A maximum of 3000 files can be returned.
    # - For more flexibility and no limitations see "Using local .git directory" above.

    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    permissions:
      pull-requests: write

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
                python-version: 3.x

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          OUTPUT=$(python ./scripts/check_changed_articles.py "$ALL_CHANGED_FILES")
          echo $OUTPUT
          #OUTPUT=$(shell command or script to extract the part your want)
           {
            echo 'MESSAGE<<EOF'
            echo $OUTPUT
            echo EOF
          } >> "$GITHUB_ENV"
        #   echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV

      - name: Create comment with annotations
        uses: mshick/add-pr-comment@v2
        with:
          message:  ${{ env.MESSAGE }}
            
